### ISSUE TITLE
Exception shown when plugin used in POM

### ISSUE THREAD

**Issue by ayld** [Codarama/diet-maven-mojo#2]
When the mojo is used like this:

``` xml
<plugin>
        <groupId>org.codarama.diet</groupId>
        <artifactId>diet-maven-mojo</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <inherited>true</inherited>
        <executions>
            <execution>
                <phase>package</phase>
                <goals>
                    <goal>minimizer</goal>
                </goals>
            </execution>
        </executions>
</plugin>
```

This is shown when the project using it is being built:

```
javax.management.MalformedObjectNameException: Invalid character `:' in value
    at javax.management.ObjectName.parseValue(ObjectName.java:974)
    at javax.management.ObjectName.checkValue(ObjectName.java:1006)
    at javax.management.ObjectName.construct(ObjectName.java:725)
    at javax.management.ObjectName.<init>(ObjectName.java:1425)
    at org.modeshape.jmx.RepositoryStatisticsBean.getObjectName(RepositoryStatisticsBean.java:98)
    at org.modeshape.jmx.RepositoryStatisticsBean.start(RepositoryStatisticsBean.java:69)
    at org.modeshape.jcr.JcrRepository$RunningState.<init>(JcrRepository.java:1007)
    at org.modeshape.jcr.JcrRepository$RunningState.<init>(JcrRepository.java:978)
    at org.modeshape.jcr.JcrRepository.doStart(JcrRepository.java:388)
    at org.modeshape.jcr.JcrRepository.login(JcrRepository.java:651)
    at org.modeshape.jcr.JcrRepository.login(JcrRepository.java:622)
    at org.modeshape.jcr.JcrRepository.login(JcrRepository.java:145)
    at org.codarama.diet.index.impl.ModeShapeLibraryIndex.<init>(ModeShapeLibraryIndex.java:65)
    at org.codarama.diet.index.impl.ModeShapeLibraryIndex.withConfig(ModeShapeLibraryIndex.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
```

Build the [test project](https://github.com/Codarama/diet-tests) for full stack.

**Comment by ayld** [comment]
This seems to be "cosmetic" as the project is still minimised regardless of this being shown.
It is probably due to the fact that the engine doesn't package the ModeShape conf file properly.
